/*
MANEJO DE MODULOS

SON ARCHIVOS QUE PERMITEN COMPARTIR PARTES DEL CODIGO CON OTROS MODULOS

SE PUEDEN COMPARTIR VARIABLES, FUNCIONES, CLASES, ENTRE OTROS. TODO ESTO ENTRE ARCHIVOS DE JS

SON UN ESTRATEGIA PARA DIVIDIR CODIGO

REEMPLAZABLE, REMOVIBLE Y FACIL DE ADAPTAR E INTEGRAR CON EL PROYECTO

EXPORTAR E IMPORTAR 





*/
