/*

OPERADORES LOGICOS

&& oeprador AND --> AMBOS VALORES SON VERDADEROS RETORNA TRUE Y SI UNO DE LOS DOS ES FALSE RETORNA FALSE

|| EL OPERADOR OR RETORNA VERDADERO SI AL MENOS UNO DE LOS VALORES ES VERDADERO DE LO CONTRARIO DEVUELVE FALSO


! OPERADOR DE NEGACION o NOT


?? EL OPERADOR NULLISH COALESCING // FUSION DE NULOS O UNION NULOSA



*/

